# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# CodeRabbit 설정 파일
# 한글 리뷰 및 develop 브랜치 지원

language: ko-KR
early_access: false
enable_free_tier: true

reviews:
    profile: chill
    request_changes_workflow: false
    high_level_summary: true
    poem: false
    review_status: true
    collapse_walkthrough: false
    auto_review:
        enabled: true
        ignore_title_keywords:
            - "WIP"
            - "DO NOT REVIEW"
        drafts: false
        base_branches:
            - main
            - develop

    path_filters:
        - "!**/*.md"
        - "!**/build/**"
        - "!**/gradle/**"
        - "!**/.gradle/**"
        - "!**/gradlew"
        - "!**/gradlew.bat"

    path_instructions:
        - path: "src/main/java/**/controller/**"
          instructions: |
              - REST API 규칙 준수 확인
              - HTTP 상태 코드 적절성 검토
              - DTO validation 확인
              - 예외 처리 검토

        - path: "src/main/java/**/service/**"
          instructions: |
              - 비즈니스 로직 복잡도 확인
              - 트랜잭션 경계 검토
              - 예외 처리 적절성 확인
              - 코드 중복 확인

        - path: "src/main/java/**/repository/**"
          instructions: |
              - JPA 쿼리 최적화 확인
              - N+1 문제 체크
              - 인덱스 사용 검토

        - path: "src/main/java/**/entity/**"
          instructions: |
              - JPA 엔티티 관계 설정 확인
              - Lazy/Eager 로딩 전략 검토
              - 양방향 관계 관리 확인

chat:
    auto_reply: true

tools:
    ruff:
        enabled: true
    markdownlint:
        enabled: false
    languagetool:
        enabled: false
        enabled_only: false
        level: default
