name: Deploy to EC2

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

env:
    AWS_REGION: ap-northeast-2
    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}   # 12자리 AWS 계정 ID
    ECR_REPO: caring-server
    IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO }}

permissions:
    id-token: write    # GitHub → AWS OIDC 필요
    contents: read

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: JDK 17버전 설치
                uses: actions/setup-java@v4
                with:
                    distribution: temurin
                    java-version: 17

            -   name: Grant execute permission for gradlew
                run: chmod +x ./gradlew

            -   name: 테스트 및 빌드하기
                run: ./gradlew clean build

            -   name: AWS Role 설정
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    role-to-assume: arn:aws:iam::430118840639:role/GitHubActionsECRDeployRole
                    aws-region: ${{ secrets.AWS_REGION }}

            -   name: ECR에 로그인
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v2

            -   name: Docker 이미지 빌드
                run: docker build -t caring-server .

            -   name: ECR에 태그 추가
                run: docker tag caring-server ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:latest

            -   name: ECR에 Docker 이미지 Push
                run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:latest

            -   name: EC2 접속 및 배포
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.EC2_HOST }}
                    username: ${{ secrets.EC2_USER }}   # ubuntu 또는 ec2-user
                    key: ${{ secrets.EC2_KEY }}
                    script: |
                        set -e
                        AWS_REGION=${{ secrets.AWS_REGION }}
                        ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
                        ECR_REPO=${{ secrets.ECR_REPO }}

                        cd /apps/caring/prod 
                        docker stop caring-server || true
                        docker rm caring-server || true
                        docker compose pull caring-server
                        docker compose up -d caring-server
                        docker image prune -f
